"""empty message

Revision ID: 15189621b92f
Revises: 
Create Date: 2018-08-17 15:21:30.969036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15189621b92f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
