"""empty message

Revision ID: 8ccc20e99531
Revises: b1e1b831f34a
Create Date: 2018-08-21 13:08:24.300829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ccc20e99531'
down_revision = 'b1e1b831f34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('txt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_txt',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('txt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['txt_id'], ['txt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_txt')
    op.drop_table('txt')
    # ### end Alembic commands ###
